language: c

compiler:
  - clang
  - gcc

script: make

sudo: required

os:
  - linux

before_install:
  - if [ `uname` = "Darwin"]; then
        brew install gcc48;
    else
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
        sudo apt-get update -qq;
        sudo apt-get install -y sudo gcc-4.8 g++-4.8;
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8;
    fi

